name: Claudephobia
options:
  bundleIdPrefix: com.claudephobia
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
targets:
  Claudephobia:
    type: application
    platform: macOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.claudephobia.app
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/Claudephobia.entitlements
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        COMBINE_HIDPI_IMAGES: true
